// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {highlight} from '../models';
import {regex} from '../models';
import {file} from '../models';

export function GetHighlightParts(arg1:highlight.HighlightRequest):Promise<Array<string>>;

export function PreviewRegexRename(arg1:any):Promise<any>;

export function RegexRename(arg1:regex.RenameRequest):Promise<regex.RenameResult>;

export function RegexRenameExecute(arg1:regex.RenameRequest):Promise<regex.RenameResult>;

export function SelectFiles():Promise<file.SelectFilesResult>;

export function ValidateRegex(arg1:string):Promise<regex.ValidateResult>;
