// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function ValidateRegex(arg1) {
  return window['go']['main']['App']['ValidateRegex'](arg1);
}
