// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHighlightParts(arg1) {
  return window['go']['main']['App']['GetHighlightParts'](arg1);
}

export function PreviewRegexRename(arg1) {
  return window['go']['main']['App']['PreviewRegexRename'](arg1);
}

export function RegexRename(arg1) {
  return window['go']['main']['App']['RegexRename'](arg1);
}

export function RegexRenameExecute(arg1) {
  return window['go']['main']['App']['RegexRenameExecute'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function ValidateRegex(arg1) {
  return window['go']['main']['App']['ValidateRegex'](arg1);
}
