// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SelectFiles():Promise<main.SelectFilesResult>;

export function ValidateRegex(arg1:string):Promise<main.RegexValidationResult>;
